#!/bin/bash

echo Using org and environment configured in /setup/setenv.sh

source ../../../setup/setenv.sh

echo "Enter the access token generated by the "token-gen" sample, followed by [ENTER]:"

read -s token

echo Making a request to retrieve the contents of the "/users" collection

curl -v -X GET -H "Authorization: Bearer $token" "http://$org-$env.$api_domain/v1/datastore/users"
